# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 黄渡的个人博客
subtitle: 记录一个程序员的成长轨迹
description: 我喜欢敲代码。I like programming.
keywords: Java,程序,技术,IT,计算机
author: 黄渡
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://huangdu94.club
root: /
permalink: :category/:title/
permalink_defaults: :category/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
plugins: hexo-generator-feed
#Feed Atom
feed:
    type: atom
    path: atom.xml
    limit: 20
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 自动生成sitemap
sitemap: 
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# baidu 主动推送
baidu_url_submit:
    count: 10 ## 比如10，代表提交最新的十个链接
    host: https://huangdu94.club ## 在百度站长平台中注册的域名
    token: Nvmy8GNuG6UfawRh ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
    path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo:
        github: git@github.com:huangdu94/huangdu94.github.io.git,master
        #coding: git@e.coding.net:huangdu/huangdu.git,master
  - type: baidu_url_submitter
